import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home()
{
  const year = new Date().getFullYear().toString()

  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About</Link>
        </nav>
      </header>

      <main className={styles.main}>
        <Link href={ }>
          <img src="" alt="" />
          <h2>Events In London</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A iure officiis labore tenetur rem magni eveniet velit dicta minus, ut, assumenda quae praesentium vel, nemo vero alias saepe unde. Quod sed quos eum reprehenderit error voluptatum tempora odio suscipit officia facilis numquam repellat, libero, velit ratione eligendi nisi magni esse?</p>
        </Link>
      </main>

      <footer className={styles.footer}>
        <p>@ {year} Some Dumbass Project</p>
      </footer>
    </>
  )
}
