import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data })
{
  const year = new Date().getFullYear().toString();

  return (
    <>
      <Head>
        <title>The Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Image src="" alt="" />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {
          data.map((ev) =>
          {
            return (<Link key={ev.id} href={`/events/${ev.id}`}>
              {/* <Image src={ev.image} width={100} height={100} /> */}
              <h1>{ev.title}</h1>
              <p>{ev.description}</p>
            </Link>)
          })
        }
      </main>

      <footer className={styles.footer}>
        <p>@ {year} Some Dumbass Project</p>
      </footer>
    </>
  );
}

export async function getServerSideProps()
{
  const { events_categories } = await import('../data/data.json')

  return {
    props: {
      data: events_categories
    }
  }
}